[APP]
# TODO: release版本改为false
DEBUG               = true

# TODO: 修改项目根目录的绝对路径
HOME_DIR            = "/home/feng/Code/lvmin_BookRecommender"

# TOOD: 可以修改为更长的,例如 256位密钥
AUTH_SECRET_KEY     = "zhbzz"

# 数据库配置
[DATABASE]
USERNAME            = "root"
PASSWORD            = "123456"
DOMAIN              = "127.0.0.1:3306"
DATABASE_NAME       = "zhbzz"
REDIS_URL           = "redis://@localhost:6379/1"
